services:
  mariadb-11:
    image: mariadb:11
    container_name: mariadb-11
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: password
    ports:
      - 4151:3306
    volumes:
      - ../../storage/mariadb/11:/var/lib/mysql
