services:
  mariadb-latest:
    image: mariadb:latest
    container_name: mariadb-latest
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: password
    ports:
      - 4150:3306
    volumes:
      - /home/mgremy/docker/storage/mariadb/latest:/var/lib/mysql

