services:
  windows-10:
    image: dockurr/windows
    container_name: windows-10
    volumes:
      - /home/mgremy/docker/storage/windows/10:/storage
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 4010:3389/tcp
      - 4010:3389/udp
    environment:
      VERSION: 10
      DISK_SIZE: "32G"
      RAM_SIZE: "4G"
      CPU_CORES: "1"
      LANGUAGE: "French"
      REGION: "fr-FR"
      KEYBOARD: "fr-FR"
    stop_grace_period: 2m
